app/models/paint.rb
db/migrate/20240213172213_create_paints.rb
db/schema.rb
test/models/paint_test.rb

creation du paint model et de ses validations

paint model

---

Gemfile
Gemfile.lock
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20240214113341_create_active_storage_tables.active_storage.rb
db/schema.rb

J'ai ajouter les configs cloudinary.
N'oubliez pas de bundle install !

ajouter les configs cloudinary

---

app/controllers/bookings_controller.rb
app/controllers/paints_controller.rb
config/routes.rb
test/controllers/bookings_controller_test.rb

fix a line in paints controller
fix bookings route
added bookings controller

Adding bookings controller

---

app/controllers/bookings_controller.rb
app/controllers/paints_controller.rb
app/models/booking.rb
app/views/bookings/_booking_form.html.erb
app/views/bookings/index.html.erb
app/views/paints/_booking_form.html.erb
app/views/paints/show.html.erb

J'ai ajouté une view booking, un formulaire booking et changer un peu le controller et la validation

add booking view et changer le controller

---

app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
db/migrate/20240214190356_add_names_to_users.rb
db/schema.rb

Ajout des colonnes first_name et last_name au model User, ainsi que les validations.
Make-over de l'inscription avec l'ajout des colonnes + bootstrap
Make-over de la connexion avec bootstrap.

ajout des names au model user et refonte de l'inscription/connexion

---

app/javascript/application.js
app/views/bookings/_booking_form.html.erb
app/views/paints/show.html.erb

Formulaire fini manque plus que le commentaire en javascript pour calculer les montants en fonction des choix de l'utilisateur

formulaire terminé

---

.gitignore
app/assets/stylesheets/components/_cards_grid.scss
app/assets/stylesheets/components/_text_on_card_index.scss
app/models/paint.rb
app/views/pages/home.html.erb
app/views/paints/index.html.erb
app/views/paints/my_paints.html.erb

1. **/my-paints**
- mise en page du grid (test effectué avec 2 users ayant des paints différentes)
2. **/index** = mise en page du grid (modifs)
* rajout d'un container (alignement horizontal identique à celui sur la home)
* j'ai changé class col-11 en col-12 (pour supprimer le décalage en début de ligne entre le titre et les cards)
* j'ai enlevé une colonne 1fr dans le component _cards_grid.scss (les images de peinture sont trop écrasées horizontalement sinon)

my-paints et autres détails

---

app/views/bookings/index.html.erb

ajout du bouton destroy dans l'index des bookings

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button_menu.scss
app/assets/stylesheets/components/_dropdown_menu.scss
app/assets/stylesheets/components/_index.scss
app/javascript/controllers/toggle_controller.js
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_old.html.erb

refonte du bouton menu

---

app/javascript/application.js
app/views/bookings/_booking_form.html.erb

les prix de la réservation s'adaptent au nombre de jours

formulaire de reservation responsive

---

app/javascript/application.js
app/views/bookings/_booking_form.html.erb

rendu le code plus lisible

---

app/assets/stylesheets/components/_avatar.scss
app/controllers/users_controller.rb
app/models/user.rb
app/views/paints/show.html.erb
app/views/shared/_navbar.html.erb
app/views/users/_form.html.erb
app/views/users/edit.html.erb
config/routes.rb
test/controllers/users_controller_test.rb

Ajout des avatars

---

app/assets/config/manifest.js
app/controllers/bookings_controller.rb
app/javascript/application.js
app/javascript/lib/price_total.js
app/models/booking.rb
app/views/bookings/_old_booking_form.html.erb
app/views/bookings/index.html.erb
config/initializers/assets.rb
db/migrate/20240218172044_add_total_price_to_bookings.rb
db/schema.rb

ajout de reduction et fix de bugs

---

app/assets/stylesheets/components/_avatar.scss
app/models/paint.rb
app/views/paints/show.html.erb
db/seeds.rb

ajout d'un user dans la seed

---

app/javascript/controllers/booking_form_controller.js
app/views/bookings/_booking_form.html.erb

transfert du javascript dans un controller stimulus pour que ça soit plus propre

transfert du javascript dans un controller stimulus

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_navbar_responsive.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_mobile.erb

la navbar change en fonction de la largeur de l'écran

---

app/views/shared/_OLD_flashes.html.erb

[retrait alert et navbar - couleur non active plus foncée]

retrait alert et navbar - couleur non active plus foncée

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_navbar_responsive.scss
app/controllers/paints_controller.rb
app/javascript/controllers/scroll_navbar_controller.js
app/models/paint.rb
app/views/bookings/_booking_form.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_search_bar.html.erb

search bar adaptative

---

app/controllers/paints_controller.rb
app/views/paints/edit.html.erb
app/views/paints/show.html.erb
app/views/shared/_navbar_mobile.erb

add edit form to show when user is the owner
fix bug that breaks the site for  non connected user in mobile navbar

ajouter form edit dans la show + fix probleme de connexion

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_searchbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/shared/_navbar.html.erb
app/views/shared/_search_bar.html.erb

css de la searchbar

---

db/seeds.rb

ajout de destroy all et de puts dans la seed

---

app/assets/stylesheets/components/_cards_grid.scss
app/assets/stylesheets/components/_mouv_cards.scss
app/assets/stylesheets/components/_searchbar.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

homepage et boutons inscription / connexion fait
